import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Eye, EyeOff, Loader2 } from "lucide-react";
import { useApplicationDependenciesCompatibility } from "@/app/composition";
import { clearRecoveryCallbackUrl } from "@/features/auth/recovery";
export default function ResetPassword() {
 const { authentication }=useApplicationDependenciesCompatibility(); const navigate=useNavigate(); const [ready,setReady]=useState<boolean|null>(null); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [visible,setVisible]=useState(false); const [message,setMessage]=useState(""); const [success,setSuccess]=useState(false); const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true; void (async()=>{const p=authentication.remoteAuthenticationProvider; const r=p?await p.restoreSession():null; if(active)setReady(Boolean(r?.success&&r.value));})(); return()=>{active=false};},[authentication.remoteAuthenticationProvider]);
 async function submit(e:FormEvent){e.preventDefault(); setMessage(""); if(password.length<8)return setMessage("Choose a password with at least 8 characters."); if(password!==confirm)return setMessage("Passwords do not match."); const p=authentication.remoteAuthenticationProvider; if(!p||!ready)return setMessage("This recovery link is expired or invalid. Request a new link or return to login."); setBusy(true); const r=await p.updatePassword(password); setBusy(false); if(!r.success)return setMessage("This recovery link is expired or invalid. Request a new link or return to login."); setSuccess(true); clearRecoveryCallbackUrl(); window.setTimeout(()=>navigate("/login",{replace:true}),1200); }
 if(ready===null)return <main className="grid min-h-[100dvh] place-items-center p-6" role="status">Checking recovery link…</main>;
 return <main className="grid min-h-[100dvh] place-items-center bg-slate-100 p-6"><form onSubmit={submit} className="w-full max-w-md space-y-5 rounded-xl bg-white p-7 shadow"><h1 className="text-2xl font-semibold">Set a new password</h1>{!ready?<p role="alert">This recovery link is expired or invalid. Request a new reset link or return to login.</p>:success?<p role="status">Password updated successfully. Redirecting to login…</p>:<><input aria-label="New Password" autoComplete="new-password" minLength={8} required type={visible?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="New Password" className="app-control w-full"/><input aria-label="Confirm Password" autoComplete="new-password" minLength={8} required type={visible?"text":"password"} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm Password" className="app-control w-full"/><button type="button" aria-label={visible?"Hide password":"Show password"} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button>{message&&<p role="alert">{message}</p>}<button disabled={busy} type="submit">{busy&&<Loader2 size={18}/>}Update password</button></>}<Link to="/login">Return to login</Link></form></main>;
}